# Generated by Django 2.0.1 on 2018-07-22 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfor',
            name='phone_number',
            field=models.PositiveIntegerField(max_length=11),
        ),
    ]
