# Generated by Django 2.0.1 on 2018-07-22 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20180722_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfor',
            name='phone_number',
            field=models.BigIntegerField(max_length=11),
        ),
    ]
