# Generated by Django 2.0.1 on 2018-07-22 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20180722_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfor',
            name='phone_number',
            field=models.IntegerField(max_length=11),
        ),
    ]
