# Generated by Django 2.0.1 on 2018-07-22 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20180722_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfor',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
